### ISSUE TITLE
Add support for RSpec describe/context/it blocks

### ISSUE THREAD

**Issue by goronfreeman** [samu/blocky#15]
Currently in RSpec specs `do/end` pairs will match, but `describe/context/it` don't match with their `end`. It would be nice to have matchers added in for those cases.

**Comment by samu** [comment]
@goronfreeman This is a cool idea, but unfortunately this package was not design to handle such cases:

1. From an implementation point of view it is not trivial to add such functionality, since the package works by analyzing tokenized lines and looking for tokens marked as keywords. Since `describe` or `it` are not keywords in the ruby language but only part of a DSL, i'd have to break out of the current concept, which would bloat the implementation.

2. I'd like to keep it simple. If i implement support for rspec, people will expect support for other DSLs, which would lead to more and more complexity in the package.

**Comment by goronfreeman** [comment]
Completely understandable! I didn't look into your implementation, but thought that that could be the case before I asked. Thanks for taking the time to consider it.
